### ISSUE TITLE
Can't set TextField css from nativescript-theme-core

### ISSUE THREAD

**Issue by Lelelo1** [shirakaba/react-nativescript#34] opened 2019-08-05 14:23 UTC
Can't use core themes on components:

```
<$TextField hint={"test"}
    className={"input input-border input-rounded"}
    onLoaded={(event) => {
        const textField = event.object as TextField;
        textField.className = "input input-border input-rounded";
    }}
/>
```

**Comment by shirakaba** [comment] 2019-08-05 15:17
Some notes on CSS handling by Martin Yankov:

> **Martin:** Both Angular and Vue have their own ways of declaring scoped css. Angular has the styles property on components and vue has the <style scoped> block. Global css is handled the same - via the app.css file at src root level.
>
> **Martin:** I think you should support the global `app.css` file and then research what is the preferred way to do scoped css in react.
>
> **Myself:** And I hadn't thought about `app.css`; is that injected into the app anyway by NativeScript Core, or do I need to import it explicitly somewhere in my framework?
> 
> **Martin:** That's a good question. I think it's handled by the core modules for all flavors. Does it work with ns react?
> 
> **Myself:** I have no idea as I don't use CSS for anything! But I found that some built-in CSS classes e.g. for Button were working, so I guess it's included by the core modules.
> 
> **Martin:** There are no built-in classes. You are probably talking about the theme, so you must have `app.css` with the theme imported.

Last time I checked, built-in classes corresponding to the Button component (e.g. `"btn btn-primary btn-active"`) appeared to actually be working. So maybe there is more than one CSS file assumed to be globally available. Are we both talking about the same CSS file here?

The problem is that I don't know the nomenclature here. What is the "core theme", where is it documented, and where does it live in the NativeScript Core codebase?

**Comment by Lelelo1** [comment] 2019-08-05 16:42
There was no bug! I have very little experience with Nativescript in general.

The `TextField` had to be in a `StackLayout class="form"` to become available. The css for `TextField` is part of [Form](https://docs.nativescript.org/ui/theme#text). This was the case in a vanilla ts Nativescript project as well.

`<$StackLayout className={"form"}>`

**Comment by shirakaba** [comment] 2019-08-05 16:52
Whew! Very relieved to hear that, as I'd imagined that the core CSS had been working. Yes, I can see it would be easy to miss that!

So, in summary, the CSS rule must have involved some inheritance like this..?

```css
.form > .input {
    <!-- Expected TextField styles went here -->
}
```

**Comment by shirakaba** [comment] 2019-08-05 17:54
Closing as, to my understanding, this wasn't a bug.

**Closed by shirakaba** 2019-08-05 17:54 UTC
Labels: bug
